title: The Azure Cosmos DB Workshop
remote_theme: azure-immersion/workshop-jekyll-theme
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge